Repository nurion4hep/GenOnHPC, pull requests merged in 2022-05, with the labels that each got.

#27 Sherpa singularity recipe
  config/singularity/rivet-sherpa.def
Labels: container

#28 Migration to use prepare.sh
  config/singularity/rivet-sherpa.def
  test/mg5/Cards/TTJets_5f_NLO_FXFX/param_card.dat
  test/mg5/scan_at_localmachine.sh
  test/powheg/scan_at_localmachine.sh
Labels: container, configurations

#29 use prepare.sh for the powheg generators
  test/powheg/generate.sh
  test/powheg/prepare.sh
Labels: generator-support

#31 rivet-herwig/pythia
  config/singularity/rivet-herwig.def
  config/singularity/rivet-pythia-powheg.def
Labels: generator-support

#32 Remove duplicated singularity def files
  config/singularity/rivet-pythia-powheg.def
  config/singularity/rivet-pythia8.def
Labels: generator-support
